# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OneScreenMVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OneScreenMVVM
  pod 'RxSwift'
  pod 'RxCocoa'
  target 'OneScreenMVVMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OneScreenMVVMUITests' do
    # Pods for testing
  end

end
