# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoreDataMVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoreDataMVVM
  pod 'RxSwift'
  pod 'QueryKit'
end
